### ISSUE TITLE
Model Enchancements

### ISSUE THREAD

**Issue by RadeKornjaca** [UKS-Tim3/Issuebox#3]
Model as is at the develop branch has some oversights so it needs to be 
- [x] Relationship between Tag and Issue entities has to be ManyToMany
- [x] Change Typo in "Priority" enumeration from "Hi" to "High"
- [x] Relationship between Contributor and Repository should be ManyToMany
- [x] Missing GitHub URL and picture URL fields for User
- [x] Missing GitHub URL and description fields for Repository

If you see any of the oversights, feel free to write in these comments.

**Comment by RadeKornjaca** [comment]
Change model:
- [x] Add support for font color on tag
- [x] Add OneToOne relationship between Commit and Issue

**Comment by danielkupco** [comment]
Some corrections to issue should be made:
- [x] When creating a tag issue should not be selected, rather, tags should be selected when creating an issue, just like with repository and contributors
- [x] Also, 'date finished' and 'assignee' fields should not be mandatory

**Comment by drilic** [comment]
- [x]  img_url attribute should not be required in Contributor entity.
- [x]  Add issue to repository relationship.
- [x]  Missing timestamp attribute for comments

**Comment by danielkupco** [comment]
- [x] hash attribute in Commit
- [x] github_url attribute in Commit
- [x] related name for Comment in Comment-Issue relation
